# Generated by Django 4.1.3 on 2022-11-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(verbose_name='Peso de la torta')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la torta')),
            ],
        ),
    ]
